name = "yt-bulk-uploader-api"
main = "backend/src/index.ts"
compatibility_date = "2024-02-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "yt-bulk-uploader-db"
database_id = "4b62cdd7-19ff-4fb7-bde7-993e9d01ae8d"